import: definition.yaml

concurrency:
  task:
    dbbench-std: 1
    alfworld-std: 5
  agent:
    vllm-model: 5

assignments:
  - agent:
      - vllm-model
    task:
      - dbbench-std
      - alfworld-std

output: "outputs/{TIMESTAMP}"
